Task one
89605502155/Ferubko_yadro_course pull request #2
Opened 2024-03-28 03:30 UTC by 89605502155

Добрый день.
Я готов представить пробную версию домашнего задания номер 1.

С Уважением, Ферубко Андрей.

2024-03-28 06:35 UTC, vbelogrudov commented
plus  @kirreal

2024-03-28 06:52 UTC, vbelogrudov requested changes
переусложнено :)

2024-03-28 06:52 UTC, vbelogrudov commented on myapp
не стоит включать бинарные файлы в репозиторий

2024-03-28 06:52 UTC, vbelogrudov commented on unused_english_words_copy.txt
нужен ли этот файл?

2024-03-28 06:52 UTC, vbelogrudov commented on testing.go
> +func main_() {
По правилам Go

- необходимо назвать функцию TestStem(t *testing.T) { ... } и включить import "testing"
- имя файла должно оканчиваться на _test.go .. например, stem_test.go

2024-03-28 06:52 UTC, vbelogrudov commented on main.go
> +func readWordsFromFile(filename string, bufferSize int, numLines int) <-chan []string {
решение переусложнено. Канал на выходе стоит заменить на просто слайс строк. У нас не должно быть много слов для чистки, поэтому нет необходимости в проверке размером буфера.

2024-03-28 06:52 UTC, vbelogrudov commented on main.go
> +	sentence := flag.String("s", "", "sentence to normalize")
лучше использовать flag.StringVar, чтобы не работать с разыменованиями указателей

2024-03-28 06:52 UTC, vbelogrudov commented on main.go
> +	for lines := range wordCh {
большай циклографическая сложность. Алгоритм должен быть достаточно простой, с одним проходом по списку слов. Внутри цикла чистим слово, отбрасываем совпадающие с unused, складываем в результирующий слайс. 

unused слова стоит поместить в "словарь", map[string]bool, и потом проверять совпадения с данными пользователем по словарю

2024-03-28 09:10 UTC, 89605502155 commented on unused_english_words_copy.txt
это копия оригинального файла со словами. Держу его на случай, если я как-то сломаю или случайно удалю исходный файл со словами, которые надо выкинуть.

2024-03-28 09:12 UTC, 89605502155 commented on testing.go
> +func main_() {
Видимо случайно забыл удалить этот файл. В нём я смотрел, как работает функционал использованных библиотек (что-то типа песочницы).  Эта операция необходима, потому что я впервые использую некоторые из библиотек.

2024-03-28 09:15 UTC, 89605502155 commented on main.go
> +func readWordsFromFile(filename string, bufferSize int, numLines int) <-chan []string {
Хорошо, переделаю. Просто я думал, что вдруг они не поместятся в оперативную память или займут слишком много места (думал о том как я бы сделал реальную систему, в которой есть проверка по многим языкам и наборам символов).

2024-03-28 09:15 UTC, 89605502155 commented on main.go
> +	sentence := flag.String("s", "", "sentence to normalize")
Спасибо за совет. Переделаю.

2024-03-28 09:17 UTC, 89605502155 commented on main.go
> +	for lines := range wordCh {
Хорошо, переделаю. Изначально так делал, потому что не хотел, чтобы словарь занимал много места.

2024-03-28 09:18 UTC, 89605502155 commented on myapp
Хорошо, учту.

2024-03-28 09:38 UTC, 89605502155 commented on main.go
> +	for lines := range wordCh {
Да, кстати, а почему вы рекомендуете использовать именно словарь, а не слайс?
Это как-то связано с памятью, или я чего-то недопонял?

2024-03-28 09:56 UTC, vbelogrudov commented on main.go
> +	for lines := range wordCh {
это про поиск в словаре и в слайсе, в первом O(n), во втором O(1). map можно использовать для stop words, их не должно быть много, не больше 1000. Иначе мы отсеем полезные. Также map можно использовать для складывания обработанных слов после стемминга, чтобы обеспечить уникальность. Таких еще меньше, так как мало кто будет вводить поисковую фразу с > 10 слов. Можно предусмотреть защиту от хакеров и обрезать поисковую строку до разумных пределов, например, не больше 100 символов.

2024-03-31 23:50 UTC, 89605502155 commented
Доброе утро!!! 
Я переделал все Ваши замечания по предыдущему решению.

С Уважением, Ферубко Андрей.

2024-04-01 07:23 UTC, vbelogrudov approved these changes
основная проблема в недостаточном разбиении, также желательно всю логику поместить в отдельную функцию, чтобы ее можно было многократно вызвать. На это можно посмотреть в следующем задании.

Ferubko_yadro_course$ ./myapp -s 'follow, followers!'
follow, followers!

2024-04-01 07:23 UTC, vbelogrudov commented on main.go
> +	for i, _ := range myWordsMap {
_ необязателен

2024-04-01 15:30 UTC, merged